server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oakindex
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: false